baseURL = 'https://x-s-singularity-notes.vercel.app/'
languageCode = 'en-us'
title = "林记蛋炒饭"
theme = "PaperMod"

[params]
    env = "production"
    title = "X's Singularity Notes"
    description = "Notes from the event horizon of thought."
    author = "X"
    
    defaultTheme = "dark"
    disableThemeToggle = true
    DateFormat = "2006/01/02 15:04"
    ShowReadingTime = true
    ShowShareButtons = false
    ShowPostNavLinks = true
    ShowBreadCrumbs = true
    ShowCodeCopyButtons = true

    [params.profileMode]
        enabled = false

[menu]
# 1. 阿明的分区入口
    [[menu.main]]
        identifier = "aming"
        name = "阿明"               # 网页顶部菜单显示的中文名
        url = "/categories/aming/"  # 指向我们刚才设置的拼音分类
        weight = 10

    # 2. 阿静的分区入口
    [[menu.main]]
        identifier = "ajing"
        name = "阿静"
        url = "/categories/ajing/"
        weight = 20
    [[menu.main]]
        identifier = "posts"
        name = "ARTICLES"
        url = "/posts/"
        weight = 10
    [[menu.main]]
        identifier = "search"
        name = "SEARCH"
        url = "/search/"
        weight = 20

[outputs]
    home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
